### ISSUE TITLE
How can offset > limit?

### ISSUE THREAD

**Issue by seishun** [dcodeIO/ByteBuffer.js#53]
The documentation for [ByteBuffer#toBuffer](https://github.com/dcodeIO/ByteBuffer.js/wiki/API#bytebuffertobufferforcecopy) states:

>Will transparently ByteBuffer#flip this ByteBuffer if offset > limit but the actual offsets remain untouched.

I might be missing something but I can't imagine a scenario where offset would be greater that limit. I think it would be more useful to flip if limit equals offset (currently it returns an empty Buffer).

**Comment by dcodeIO** [comment]
Let's say you have a ByteBuffer with a capacity of 2. It is instanciated with offset=0, limit=2.

Now you write 1 byte to it, making offset=1, and call `ByteBuffer#flip` to match your written contents, making limit=offset=1, offset=0.

Afterwards, you write 2 bytes to it, making offset=2 (**limit still is 1**), calling `ByteBuffer.flip` again to match your written contents, making limit=offset=2, offset=0.

The phrasing refers to this scenario, but the last call to `ByteBuffer#flip` has been omitted. While it is still valid, it is more or less left over from previous versions of ByteBuffer, which instantiated with offset=limit=0, which was changed in order to match the bahavior of Java ByteBuffers more closely. It's not as powerful anymore, as the reverse scenario (first writing 2, then 1 bytes, then missing the final flip), can not be corrected.

**Comment by seishun** [comment]
I see, so the recommended way to is to always flip yourself before calling toBuffer?

**Comment by dcodeIO** [comment]
Yes, as this makes sure that it returns the exact intended portion of bytes.

**Comment by seishun** [comment]
Thanks, this clarifies things.

**Comment by dcodeIO** [comment]
FYI: https://github.com/dcodeIO/ByteBuffer.js/commit/5d089a39d8e0b917eb7a0168ce85303df1417093

**Comment by seishun** [comment]
Now it will throw in the scenario you described, right?

**Comment by dcodeIO** [comment]
If `noAssert=false`, yes.

**Comment by seishun** [comment]
`new ArrayBuffer` with a negative argument would throw anyway. Maybe it should be noted that limit must be greater or equal to offset.
